### PR TITLE
Assorted typo fixes.

### LINKED ISSUE #52: Typos?
@XhmikosR Could you please do your typo check here too?

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #52 

/CC @refack

### CODE REVIEW

**Review by cclauss — APPROVED** [review]
LGTM

**Comment by XhmikosR** [comment]
@cclauss can you merge this?

**Comment by cclauss** [comment]
Sorry.  I do not have admin rights on this repo.

**Comment by XhmikosR** [comment]
NP, @refack friendly ping

**Comment by XhmikosR** [comment]
Closing since it's been so many months.

**Pull request closed without merging**
